require release notes...

diff --git a/sbin/dist-validate-env b/sbin/dist-validate-env
--- a/sbin/dist-validate-env
+++ b/sbin/dist-validate-env
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+die() {
+
+    message="${1}"
+    echo "ERROR: ${message}" > /dev/stderr
+    exit 1
+
+}
+
 ## make sure we are logged in via NPM
 validate_npm_auth() {
     echo "Validating npm auth..."
@@ -18,6 +26,21 @@ validate_firebase_auth() {
 
 }
 
+### make sure this version has release notes so that they're added on the whats new splash
+validate_release_notes() {
+
+    version=$(cat lerna.json | jq -r .version)
+
+    release_metadata_path="packages/polar-app-public/polar-release-metadata/src/release-metadata.json"
+
+    has_ver=$(cat ${release_metadata_path} | jq -r ".[].id" | grep ${version} | tail)
+
+    if [ "${has_ver}" = "" ]; then
+        die "No release notes for version: ${version}"
+    fi
+
+}
+
 ## make sure we have the credentials wwe need
 validate_credentials() {
 
@@ -32,6 +55,7 @@ validate_credentials() {
 
 set -e
 
+validate_release_notes
 validate_npm_auth
 validate_snapcraft_auth
 validate_firebase_auth
